[package]
name = "lorapress-cli"
version = "0.1.1"
edition = "2021"
description = "Universal compression and decompression CLI for LoRa and Meshtastic"
license = "MIT OR Apache-2.0"
readme = "../../README.md"
repository = "https://github.com/fursyt12/lora-press"
keywords = ["lora", "meshtastic", "compression", "cli"]
categories = ["command-line-utilities", "compression"]

[[bin]]
name = "lorapress"
path = "src/main.rs"

[dependencies]
lorapress-core = { path = "../lorapress-core", version = "0.1.1" }
clap = { version = "4.5", features = ["derive"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
serde_json = "1.0"
hex = "0.4"
